version: '3.8'

services:
  ollama_service:
    build: .
    group_add:
      - video
    devices:
      - "/dev/dri:/dev/dri"  
      - "/dev/kfd:/dev/kfd"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
    ports:
      - "5000:11434"
    command: ["/bin/bash"]
    tty: true
    security_opt:
      - seccomp:unconfined
    privileged: true
